# Generated by Django 4.0.4 on 2022-05-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_article_comment_task_remove_comment_pub_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
