# Generated by Django 4.0.4 on 2022-05-26 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_article_delete_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
    ]
